name: Update Jio (__hdnea__) playlist as jstar.m3u

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update-jstar-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch playlist
        run: |
          HEADER_FILE=header.m3u
          BODY_FILE=body.m3u
          TEMP_FILE=temp.m3u

          echo '#EXTM3U x-tvg-url="https://fakeall12398-sketch.github.io/JIO_TV/jio_epg.xml.gz"' > $HEADER_FILE
          echo "#Generated on $(date +%s)" >> $HEADER_FILE

          curl -L -s -o $TEMP_FILE "https://livetv-cb7.pages.dev/hotstar"

          grep -vE '^#EXTM3U|^#Generated on' $TEMP_FILE > $BODY_FILE || true

          cat $HEADER_FILE $BODY_FILE > jstar.m3u

          rm -f $HEADER_FILE $BODY_FILE $TEMP_FILE

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add jstar.m3u
          git commit -m "Auto update playlist" || echo "No changes"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
