name: Update Cricket Playlist
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:
env:
  SRC1: ${{ secrets.SOURCE_PLAYLIST1 }}
  SRC2: ${{ secrets.SOURCE_PLAYLIST2 }}
  SRC3: ${{ secrets.SOURCE_PLAYLIST3 }}
jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate playlist
        run: |
          set +e
          mkdir -p "Playlist/Cricket.m3u"
          WORKDIR="Playlist/Cricket.m3u"
          echo '#EXTM3U' > /tmp/output.m3u
          echo '# Credit: RKDYIPTV Cricket Playlist' >> /tmp/output.m3u
          echo "#Updated $(date)" >> /tmp/output.m3u
          curl -L -s --max-redirs 10 --retry 3 \
            -H "User-Agent: Mozilla/5.0" \
            "$SRC1" | grep -v -E "Abu SAEEID|Github @abusaeeidx|Update on|Note:|#EXTM3U" >> /tmp/output.m3u
          curl -L -s --max-redirs 10 --retry 3 \
            -H "User-Agent: Mozilla/5.0" \
            "$SRC2" | grep -v '^#EXTM3U' >> /tmp/output.m3u
          curl -L -s --max-redirs 10 --retry 3 \
            -H "User-Agent: Mozilla/5.0" \
            "$SRC3" | grep -v '^#EXTM3U' >> /tmp/output.m3u
          echo '<!DOCTYPE html><html><script>window.location.href="https://telegram.me/rkdyiptv";</script></html>' > /tmp/html.txt
          cat /tmp/html.txt /tmp/output.m3u > "$WORKDIR/index.html"
      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update Cricket playlist $(date)" || echo "No changes"
      - name: Push
        run: git push
